"""Build a numbered visual acceptance document; publishing is deliberately external."""

from markstitch import (
    YFM,
    Bold,
    BulletList,
    Cell,
    Checklist,
    Code,
    CodeBlock,
    Color,
    Comment,
    Cut,
    Emoji,
    File,
    Grid,
    Heading,
    Highlight,
    Iframe,
    Image,
    Italic,
    Layout,
    LineBreak,
    Link,
    LinkDefinition,
    ListItem,
    Math,
    MathBlock,
    Mention,
    Monospace,
    Note,
    NumberedList,
    PageTree,
    Paragraph,
    Profile,
    Quote,
    RawHTML,
    ReferenceImage,
    ReferenceLink,
    Row,
    Rule,
    Strike,
    StyledBlock,
    Subscript,
    Superscript,
    Tab,
    Table,
    Tabs,
    Task,
    Toc,
    Underline,
    WikiInclude,
    YFMTable,
)


def build_document(
    *,
    profile: Profile,
    image_url: str,
    file_url: str,
    wiki_page: str,
    grid_id: str,
) -> YFM:
    document = YFM(
        Heading("Markstitch — live validation", level=1),
        Paragraph(f"Profile: {profile.value}. Suite marker: YFM_LIVE_20261004."),
        Note(
            "This is a test page. An API check confirms that the text was saved; "
            "visual verification is still pending. Reference the section code Cxx/Wxx when reporting an issue.",
            kind="info",
            title="How to verify",
        ),
        Heading("C01. Headings and anchors", level=2, anchor="c01"),
        Heading("Level one", level=1),
        Heading("Level two", level=2),
        Heading("Level three", level=3),
        Heading("Level four", level=4),
        Heading("Level five", level=5),
        Heading("Level six", level=6),
        Heading("Collapsible heading", level=3, collapsible=True),
        Paragraph("This paragraph should collapse together with the heading."),
        Heading("C02. Inline formatting", level=2),
        Paragraph(
            Bold("Bold"),
            " / ",
            Italic("italic"),
            " / ",
            Underline("underlined"),
            " / ",
            Strike("strikethrough"),
            " / ",
            Highlight("highlighted"),
            " / ",
            Monospace("monospace"),
            " / x",
            Superscript("2"),
            " / H",
            Subscript("2"),
            "O / ",
            Bold(Italic("nested formatting")),
        ),
        Paragraph(
            *[
                item
                for color in ("gray", "yellow", "orange", "red", "green", "blue", "violet")
                for item in (Color(color, color=color), " ")
            ][:-1]
        ),
        Heading("C03. Escaping and line breaks", level=2),
        Paragraph(
            "Should remain plain text: **not bold**, [not link](example.com), {% cut no %}, <b>literal</b>, &amp;."
        ),
        Paragraph("First line", LineBreak(), "Second line"),
        Heading("C04. Links", level=2),
        Paragraph(
            Link("Plain link", "https://example.com", title="Tooltip"),
            " / ",
            Link(Bold("Bold link"), "https://example.com"),
            " / ",
            Link("Go to anchor C01", "#c01"),
        ),
        Heading("C05. Lists and nesting", level=2),
        NumberedList(ListItem("First", BulletList("Subitem A", "Subitem B")), "Second", start=9, loose=True),
        BulletList("Tight list", "Second item"),
        Paragraph("A separate loose list follows:"),
        BulletList("Loose list", "Second item", loose=True),
        Heading("C06. Checklists", level=2),
        Checklist(Task("Checked", checked=True), Task("Unchecked")),
        Heading("C07. Quotes", level=2),
        Quote(Paragraph("Quote with ", Bold("formatting")), Quote("Nested quote")),
        Heading("C08. Code", level=2),
        Paragraph("Inline: ", Code("SELECT `id`")),
        CodeBlock("print('YFM_CODE_OK')\nprint(1 + 2)", language="python", line_numbers=True, wrap=True),
        CodeBlock("```\n{% endcut %}\n#|\n```", language="text"),
        Heading("C09. Formulas", level=2),
        Paragraph("Inline: ", Math("e^{ix}=\\cos x+i\\sin x")),
        MathBlock("\\sum_{k=1}^{3} k = 6"),
        Heading("C10. Notes", level=2),
        *(Note("Note content", kind=kind, title=f"Kind: {kind}") for kind in ("info", "tip", "warning", "alert")),
        Heading("C11. Cuts", level=2),
        Cut(
            "Outer cut",
            Paragraph("Inside: ", Link("link", "https://example.com")),
            Cut('Nested cut with "quotes"', "YFM_NESTED_CUT_OK"),
        ),
        Heading("C12. Tabs", level=2),
        Tabs(Tab("Linux", NumberedList("Install", "Run")), Tab("macOS", Note("YFM_TAB_OK", kind="tip"))),
        Heading("C13. Simple table", level=2),
        Table(
            ["Left", "Center", "Right"],
            [["a|b", Code("x|y"), Link("link", "https://example.com")]],
            align=["left", "center", "right"],
        ),
        Heading("C14. Multiline table", level=2),
        YFMTable(
            Row(Bold("Blocks"), Bold("Nested table")),
            Row(
                Cell(BulletList("one", "two"), CodeBlock("print(1)", language="python")),
                Cell(YFMTable(Row("A", "B"), Row("1", "2"))),
            ),
        ),
        Heading("C15. Mermaid", level=2),
        CodeBlock("graph LR\n  A[Start] --> B[Done]", language="mermaid"),
        Heading("C16. Styling and columns", level=2),
        StyledBlock("YFM_BLOCK_OK", align="center", width=400, padding="m", border="solid", border_color="tip"),
        Layout(StyledBlock("Left column", col=4), StyledBlock("Right column", col=8)),
        Heading("C17. Images", level=2),
        Paragraph(
            "Expected: a blue 64×64 square: ",
            Image(image_url, alt="Blue square", title="YFM_IMAGE_OK", width=64, height=64),
        ),
        Paragraph(Link(Image(image_url, alt="Clickable square", width=32), "https://example.com")),
        Heading("C18. File", level=2),
        Paragraph("The downloaded file should contain YFM_FILE_OK."),
        File(file_url, "yfm-test.txt", mime_type="text/plain"),
        Heading("C19. Emoji and mention", level=2),
        Paragraph(Emoji("smile"), " / ", Mention("lerik-pavlov")),
        Heading("C20. HTML block", level=2),
        RawHTML('<p style="color: green"><strong>YFM_HTML_OK</strong></p>'),
        Heading("C21. Hidden comment and separator", level=2),
        Comment("YFM_HIDDEN_COMMENT — visible only in the source markup"),
        Rule(),
        Heading("C22. Reference links", level=2),
        Paragraph(
            ReferenceLink("Reference link", "live-link"), " / ", ReferenceImage("Reference image", "live-image")
        ),
        LinkDefinition("live-link", "https://example.com", title="Reference title"),
        LinkDefinition("live-image", image_url),
        profile=profile,
    )

    if profile == Profile.WIKI:
        document.children += (
            Heading("W01. Table of contents", level=2),
            Toc(start=2, end=2),
            Heading("W02. Include another page", level=2),
            Paragraph("YFM_INCLUDE_OK should appear below."),
            WikiInclude(f"{wiki_page}/include-source", start="included", end="end"),
            Heading("W03. Page tree", level=2),
            PageTree(wiki_page, depth=2),
            Heading("W04. Dynamic grid", level=2),
            Paragraph("Expected: two rows, one containing YFM_GRID_OK."),
            Grid(grid_id, readonly=True),
            Heading("W05. Iframe", level=2),
            Paragraph("Embedded test video. Display depends on the service's allowed domains and CSP."),
            Iframe("https://www.youtube-nocookie.com/embed/aqz-KE-bpKQ", width=480, height=270),
        )

    document.children += (Heading("End of suite", level=2), Paragraph("YFM_LIVE_END_20261004"))
    return document
